//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMain.ServiceGraphics {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GraphicsData", Namespace="webgraphics")]
    [System.SerializableAttribute()]
    public partial class GraphicsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.Line[] LinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.Point InterPointField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        private int WidthField;
        
        private int HeightField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WebMain.ServiceGraphics.Line[] Lines {
            get {
                return this.LinesField;
            }
            set {
                if ((object.ReferenceEquals(this.LinesField, value) != true)) {
                    this.LinesField = value;
                    this.RaisePropertyChanged("Lines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebMain.ServiceGraphics.Point InterPoint {
            get {
                return this.InterPointField;
            }
            set {
                if ((object.ReferenceEquals(this.InterPointField, value) != true)) {
                    this.InterPointField = value;
                    this.RaisePropertyChanged("InterPoint");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Width {
            get {
                return this.WidthField;
            }
            set {
                if ((this.WidthField.Equals(value) != true)) {
                    this.WidthField = value;
                    this.RaisePropertyChanged("Width");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Height {
            get {
                return this.HeightField;
            }
            set {
                if ((this.HeightField.Equals(value) != true)) {
                    this.HeightField = value;
                    this.RaisePropertyChanged("Height");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Point", Namespace="webgraphics")]
    [System.SerializableAttribute()]
    public partial class Point : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.ExtensionDataObject ExtensionData1Field;
        
        private float XField;
        
        private float YField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WebMain.ServiceGraphics.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float X {
            get {
                return this.XField;
            }
            set {
                if ((this.XField.Equals(value) != true)) {
                    this.XField = value;
                    this.RaisePropertyChanged("X");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float Y {
            get {
                return this.YField;
            }
            set {
                if ((this.YField.Equals(value) != true)) {
                    this.YField = value;
                    this.RaisePropertyChanged("Y");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Line", Namespace="webgraphics")]
    [System.SerializableAttribute()]
    public partial class Line : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.ExtensionDataObject ExtensionData1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.Point AField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebMain.ServiceGraphics.Point BField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="ExtensionData", EmitDefaultValue=false)]
        public WebMain.ServiceGraphics.ExtensionDataObject ExtensionData1 {
            get {
                return this.ExtensionData1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ExtensionData1Field, value) != true)) {
                    this.ExtensionData1Field = value;
                    this.RaisePropertyChanged("ExtensionData1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebMain.ServiceGraphics.Point A {
            get {
                return this.AField;
            }
            set {
                if ((object.ReferenceEquals(this.AField, value) != true)) {
                    this.AField = value;
                    this.RaisePropertyChanged("A");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebMain.ServiceGraphics.Point B {
            get {
                return this.BField;
            }
            set {
                if ((object.ReferenceEquals(this.BField, value) != true)) {
                    this.BField = value;
                    this.RaisePropertyChanged("B");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExtensionDataObject", Namespace="webgraphics")]
    [System.SerializableAttribute()]
    public partial class ExtensionDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="webgraphics", ConfigurationName="ServiceGraphics.WebGRSoap")]
    public interface WebGRSoap {
        
        // CODEGEN: Generating message contract since element name gdata from namespace webgraphics is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="webgraphics/GetImage", ReplyAction="*")]
        WebMain.ServiceGraphics.GetImageResponse GetImage(WebMain.ServiceGraphics.GetImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="webgraphics/GetImage", ReplyAction="*")]
        System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetImageResponse> GetImageAsync(WebMain.ServiceGraphics.GetImageRequest request);
        
        // CODEGEN: Generating message contract since element name gdata from namespace webgraphics is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="webgraphics/GetSVGImage", ReplyAction="*")]
        WebMain.ServiceGraphics.GetSVGImageResponse GetSVGImage(WebMain.ServiceGraphics.GetSVGImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="webgraphics/GetSVGImage", ReplyAction="*")]
        System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetSVGImageResponse> GetSVGImageAsync(WebMain.ServiceGraphics.GetSVGImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImage", Namespace="webgraphics", Order=0)]
        public WebMain.ServiceGraphics.GetImageRequestBody Body;
        
        public GetImageRequest() {
        }
        
        public GetImageRequest(WebMain.ServiceGraphics.GetImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="webgraphics")]
    public partial class GetImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebMain.ServiceGraphics.GraphicsData gdata;
        
        public GetImageRequestBody() {
        }
        
        public GetImageRequestBody(WebMain.ServiceGraphics.GraphicsData gdata) {
            this.gdata = gdata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetImageResponse", Namespace="webgraphics", Order=0)]
        public WebMain.ServiceGraphics.GetImageResponseBody Body;
        
        public GetImageResponse() {
        }
        
        public GetImageResponse(WebMain.ServiceGraphics.GetImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="webgraphics")]
    public partial class GetImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetImageResult;
        
        public GetImageResponseBody() {
        }
        
        public GetImageResponseBody(string GetImageResult) {
            this.GetImageResult = GetImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSVGImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSVGImage", Namespace="webgraphics", Order=0)]
        public WebMain.ServiceGraphics.GetSVGImageRequestBody Body;
        
        public GetSVGImageRequest() {
        }
        
        public GetSVGImageRequest(WebMain.ServiceGraphics.GetSVGImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="webgraphics")]
    public partial class GetSVGImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebMain.ServiceGraphics.GraphicsData gdata;
        
        public GetSVGImageRequestBody() {
        }
        
        public GetSVGImageRequestBody(WebMain.ServiceGraphics.GraphicsData gdata) {
            this.gdata = gdata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSVGImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSVGImageResponse", Namespace="webgraphics", Order=0)]
        public WebMain.ServiceGraphics.GetSVGImageResponseBody Body;
        
        public GetSVGImageResponse() {
        }
        
        public GetSVGImageResponse(WebMain.ServiceGraphics.GetSVGImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="webgraphics")]
    public partial class GetSVGImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetSVGImageResult;
        
        public GetSVGImageResponseBody() {
        }
        
        public GetSVGImageResponseBody(System.Xml.Linq.XElement GetSVGImageResult) {
            this.GetSVGImageResult = GetSVGImageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebGRSoapChannel : WebMain.ServiceGraphics.WebGRSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebGRSoapClient : System.ServiceModel.ClientBase<WebMain.ServiceGraphics.WebGRSoap>, WebMain.ServiceGraphics.WebGRSoap {
        
        public WebGRSoapClient() {
        }
        
        public WebGRSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebGRSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebGRSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebGRSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebMain.ServiceGraphics.GetImageResponse WebMain.ServiceGraphics.WebGRSoap.GetImage(WebMain.ServiceGraphics.GetImageRequest request) {
            return base.Channel.GetImage(request);
        }
        
        public string GetImage(WebMain.ServiceGraphics.GraphicsData gdata) {
            WebMain.ServiceGraphics.GetImageRequest inValue = new WebMain.ServiceGraphics.GetImageRequest();
            inValue.Body = new WebMain.ServiceGraphics.GetImageRequestBody();
            inValue.Body.gdata = gdata;
            WebMain.ServiceGraphics.GetImageResponse retVal = ((WebMain.ServiceGraphics.WebGRSoap)(this)).GetImage(inValue);
            return retVal.Body.GetImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetImageResponse> WebMain.ServiceGraphics.WebGRSoap.GetImageAsync(WebMain.ServiceGraphics.GetImageRequest request) {
            return base.Channel.GetImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetImageResponse> GetImageAsync(WebMain.ServiceGraphics.GraphicsData gdata) {
            WebMain.ServiceGraphics.GetImageRequest inValue = new WebMain.ServiceGraphics.GetImageRequest();
            inValue.Body = new WebMain.ServiceGraphics.GetImageRequestBody();
            inValue.Body.gdata = gdata;
            return ((WebMain.ServiceGraphics.WebGRSoap)(this)).GetImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebMain.ServiceGraphics.GetSVGImageResponse WebMain.ServiceGraphics.WebGRSoap.GetSVGImage(WebMain.ServiceGraphics.GetSVGImageRequest request) {
            return base.Channel.GetSVGImage(request);
        }
        
        public System.Xml.Linq.XElement GetSVGImage(WebMain.ServiceGraphics.GraphicsData gdata) {
            WebMain.ServiceGraphics.GetSVGImageRequest inValue = new WebMain.ServiceGraphics.GetSVGImageRequest();
            inValue.Body = new WebMain.ServiceGraphics.GetSVGImageRequestBody();
            inValue.Body.gdata = gdata;
            WebMain.ServiceGraphics.GetSVGImageResponse retVal = ((WebMain.ServiceGraphics.WebGRSoap)(this)).GetSVGImage(inValue);
            return retVal.Body.GetSVGImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetSVGImageResponse> WebMain.ServiceGraphics.WebGRSoap.GetSVGImageAsync(WebMain.ServiceGraphics.GetSVGImageRequest request) {
            return base.Channel.GetSVGImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebMain.ServiceGraphics.GetSVGImageResponse> GetSVGImageAsync(WebMain.ServiceGraphics.GraphicsData gdata) {
            WebMain.ServiceGraphics.GetSVGImageRequest inValue = new WebMain.ServiceGraphics.GetSVGImageRequest();
            inValue.Body = new WebMain.ServiceGraphics.GetSVGImageRequestBody();
            inValue.Body.gdata = gdata;
            return ((WebMain.ServiceGraphics.WebGRSoap)(this)).GetSVGImageAsync(inValue);
        }
    }
}
